language: node_js
node_js: node
services: mongodb
env: MONGODB_URI=mongodb://localhost:27017/notes
deploy:
  provider: heroku
  app: thebestnotetakingapp
  api_key:
    secure: Qn8rFL0SbuR3JOCdElnn+59s4npeIzeYjCGqhYeU/6G3cPK75CPQG4D+t4fHibceWZ3/WPxMLh+pQCfsRIVFOOHkebQMJ3kAiEAJeJvfGZQ1Yilw7oRPQ8stRe9h3ERUXnur3jqZfCZ6UNPqYXJ3h7Mh6+7UKj4YOHOTtZ4enIgfzIZav0QobkNOoWhMMHzsuQYNqmJy1PtFRg40+agqmpT8zyAkD8dyurKVTo9wqVNtZveEZa7nbxwmgr7Rxk0Tun5BFGIJq2U+E0uF6lfmEB9T210fmET1PCSva1WRNUjA3MtywVDXJBY0KSBbjh+iHi1xiEw6zjzJRYgpmndd6FeZl9ht1wbF+48m4bMdK3OKeF3zbYPP6LSs3NhonHac7QkBMauUzQcaP6D5O89f3zFtx9i2vlIMtMKgii3WkSVlPTZYST45ByXZ8iOhnDHDizYhbPkga9a2KpwbO96vTjY5SDPY5wVOyx2fjYVwjU6dsTYYslFUwnTAfQusLYZZf9CVQXhtEZwm5dAXc+JMva0/E2lgN/a87dxPINriXZ9z/fwCTaYG78nZkWAy6+oChkFHrqlceqOP8B4jgUeSeoqpJBR00JVO4xTiI8D3pkm/4G1qbM9wOsNV839w7yb39HDiDoio6fC/fo8HY/4XyUIx4W7+BuSnAB1a7c1sG0U=
